# Generated by Django 5.0.2 on 2024-03-05 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('no_trabajador', models.CharField(default='', max_length=30, unique=True)),
                ('nombreU', models.CharField(default='', max_length=50)),
                ('apellido_paternoU', models.CharField(default='', max_length=50)),
                ('apellido_maternoU', models.CharField(default='', max_length=50)),
                ('cedula_profesional', models.CharField(default='', max_length=30, unique=True)),
                ('telefono', models.CharField(default='', max_length=10)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('rol', models.IntegerField(choices=[(1, 'Administrador'), (2, 'Recepcionista General'), (3, 'Recepcionista Psicologia'), (4, 'Enfermero'), (5, 'Medico General'), (6, 'Odontologo'), (8, 'Psicologo'), (7, 'Nutriologo')])),
            ],
            options={
                'verbose_name': 'usuario',
                'verbose_name_plural': 'usuarios',
            },
        ),
    ]
