# Generated by Django 5.0.3 on 2024-03-14 22:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('curp', models.CharField(default='', max_length=18)),
                ('no_expediente', models.CharField(default='', max_length=168, primary_key=True, serialize=False)),
                ('datosPersonalesPacient', models.JSONField()),
                ('datosContactoPacient', models.JSONField()),
                ('datosDireccionPacient', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('datosPersonales', models.JSONField()),
                ('cedula_profesional', models.CharField(default='', max_length=30)),
                ('no_trabajador', models.CharField(default='', max_length=30, primary_key=True, serialize=False, unique=True)),
                ('ocupacion', models.TextField(default='', max_length=20)),
                ('telefono', models.CharField(default='', max_length=10)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HistorialMedico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_elaboracion', models.DateField(auto_now_add=True)),
                ('referenciaMed', models.JSONField()),
                ('interrogatorio', models.JSONField()),
                ('exploracionFisica', models.JSONField()),
                ('diagnostico', models.JSONField()),
                ('informante', models.CharField(blank=True, default='', max_length=15)),
                ('datosFamiliares', models.JSONField()),
                ('antHerediPatM', models.JSONField()),
                ('antPersoPatM', models.JSONField()),
                ('antPersoNoPatM', models.JSONField()),
                ('ginecobMed', models.JSONField()),
                ('estudiosExter', models.JSONField()),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sistema_dif.empleado')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sistema_dif.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='HistorialOdonto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_elaboracion', models.DateField(auto_now_add=True)),
                ('referencia', models.JSONField()),
                ('aparatosSistemas', models.JSONField()),
                ('padecimiento_actual', models.TextField(blank=True, default='', max_length=100)),
                ('habitos_exteriores', models.TextField(blank=True, default='', max_length=100)),
                ('cabeza', models.JSONField()),
                ('cuello_odont', models.CharField(blank=True, default='', max_length=50)),
                ('antHerediPato', models.JSONField()),
                ('antPersonPato', models.JSONField()),
                ('personNoPato', models.JSONField()),
                ('antGinecob', models.JSONField()),
                ('odontograma', models.BinaryField(blank=True, max_length=40, null=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sistema_dif.empleado')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sistema_dif.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='NotaEvolucionOdonto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnostico', models.TextField(default='', max_length=100)),
                ('tratamiento', models.TextField(default='', max_length=100)),
                ('notas', models.TextField(default='', max_length=100)),
                ('plan', models.TextField(default='', max_length=100)),
                ('resumen_consulta', models.TextField(default='', max_length=100)),
                ('histlOdonto', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sistema_dif.historialodonto')),
            ],
        ),
        migrations.CreateModel(
            name='NotaMedica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnostico', models.TextField(default='', max_length=100)),
                ('tratamiento', models.TextField(default='', max_length=100)),
                ('observaciones', models.TextField(blank=True, default='', max_length=100)),
                ('fecha_consulta', models.DateField(auto_now_add=True)),
                ('hora_consulta', models.TimeField()),
                ('servicio', models.CharField(blank=True, default='', max_length=50)),
                ('histMedic', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sistema_dif.historialmedico')),
            ],
        ),
        migrations.CreateModel(
            name='FichaTecnicaPsicologia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_visita', models.DateField(auto_now_add=True)),
                ('visita', models.JSONField()),
                ('tratamiento', models.JSONField()),
                ('diagnostico', models.JSONField()),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sistema_dif.empleado')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sistema_dif.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='FichaTecnicaEnfermeria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('signosVitales', models.JSONField()),
                ('datosFisicos', models.JSONField()),
                ('servicio_enfermeria', models.CharField(default='', max_length=30)),
                ('trabajador', models.BooleanField(blank=True, null=True)),
                ('datosDemograficos', models.JSONField()),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sistema_dif.empleado')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sistema_dif.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='AnexoDocumentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento', models.BinaryField(blank=True, max_length=40, null=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sistema_dif.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicamento', models.JSONField()),
                ('notMed', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sistema_dif.notamedica')),
            ],
        ),
    ]
