# Generated by Django 5.0.3 on 2024-03-06 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_dif', '0002_usuario_admin_usuario_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='staff',
            field=models.BooleanField(default=True),
        ),
    ]
