# Generated by Django 5.0.2 on 2024-04-05 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_dif', '0002_remove_empleado_datospersonales_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='area',
            field=models.CharField(default='', max_length=50),
        ),
    ]
