# Generated by Django 5.0.2 on 2024-04-15 21:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_dif', '0003_paciente_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='notaevolucionodonto',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
