# Generated by Django 5.0.3 on 2024-04-19 02:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_dif', '0005_alter_notaevolucionodonto_fecha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historialmedico',
            name='empleado',
        ),
        migrations.RemoveField(
            model_name='historialmedico',
            name='paciente',
        ),
        migrations.RemoveField(
            model_name='historialodonto',
            name='empleado',
        ),
        migrations.RemoveField(
            model_name='historialodonto',
            name='paciente',
        ),
        migrations.CreateModel(
            name='FichaTecnicaMedica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnostico', models.TextField(default='', max_length=100)),
                ('motivo_consulta', models.TextField(default='', max_length=100)),
                ('observacion', models.TextField(default='', max_length=100)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sistema_dif.empleado')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sistema_dif.paciente')),
            ],
        ),
        migrations.AddField(
            model_name='historialmedico',
            name='fichaMed',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.DO_NOTHING, to='sistema_dif.fichatecnicamedica'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historialodonto',
            name='fichaMed',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.DO_NOTHING, to='sistema_dif.fichatecnicamedica'),
            preserve_default=False,
        ),
    ]
