# Generated by Django 5.0.3 on 2024-04-19 04:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_dif', '0006_remove_historialmedico_empleado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historialodonto',
            name='fichaMed',
        ),
        migrations.AddField(
            model_name='historialodonto',
            name='empleado',
            field=models.ForeignKey(default='null', on_delete=django.db.models.deletion.DO_NOTHING, to='sistema_dif.empleado'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historialodonto',
            name='paciente',
            field=models.ForeignKey(default='null', on_delete=django.db.models.deletion.DO_NOTHING, to='sistema_dif.paciente'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='FichaTecnicaMedOdonto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnostico', models.TextField(default='', max_length=100)),
                ('motivo_consulta', models.TextField(default='', max_length=100)),
                ('observacion', models.TextField(default='', max_length=100)),
                ('notaEvo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sistema_dif.notaevolucionodonto')),
            ],
        ),
    ]
