# Generated by Django 5.0.2 on 2024-04-25 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_dif', '0007_remove_historialodonto_fichamed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichatecnicamedica',
            name='extras',
            field=models.JSONField(default='', max_length=100),
        ),
    ]
