# Generated by Django 5.0.2 on 2024-04-29 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_dif', '0008_fichatecnicamedica_extras'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AnexoDocumentos',
        ),
    ]
