# Generated by Django 5.0.3 on 2024-05-04 15:22

import sistema_dif.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_dif', '0009_delete_anexodocumentos'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialmedico',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to=sistema_dif.models.ruta_documento_Odon),
        ),
        migrations.AddField(
            model_name='historialodonto',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to=sistema_dif.models.ruta_documentoMed),
        ),
    ]
