# Generated by Django 5.0.2 on 2024-05-22 19:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_dif', '0010_historialmedico_archivo_historialodonto_archivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichatecnicamedica',
            name='fecha',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
