# Generated by Django 5.0.2 on 2024-06-20 01:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_dif', '0011_fichatecnicamedica_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='receta',
            name='fecha',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
