# Generated by Django 5.0.2 on 2024-08-08 22:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_dif', '0013_fichatecnicamedodonto_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichatecnicamedica',
            name='ficha_enfermeria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='sistema_dif.fichatecnicaenfermeria'),
            preserve_default=False,
        ),
    ]
